= Caddy and Let's Encrypt 
:date: 2015/11/11 
:draft: false 
:keywords: Open Source
:description: Free TLS certificates on a really smooth web server
:slug: caddy-and-let-s-encrypt 
:image_url: images/uploads/27a382860fef4a198f01f5a6aba24d57.jpg   
:image_credit: Caddy and Let's Encrypt   
:image_credit_url: '#' 

Caddy supports Let's Encrypt automatically

== Caddy and LE

I spent all of 5 minutes configuring https://caddyserver.com[Caddy] to automatically pull content from github, post-process it with http://gohugo.io[hugo] and serve it up with fresh SSL/TLS certificates from Let's Encrypt.

When you think about it, that's pretty damned amazing.
Caddy already made web serving easy.
It powers everything I do now: gopheracademy.com, gophercon.com and a dozen more.
Add hugo to the mix and you have a really powerful publishing platform that is fully automated with just a git push.
I really love that Caddy polls my github repository and publishes new content.
It's a zero-overhead proposition to publish a new post.

After configuring the Let's Encrypt integration, my esteem for Caddy leveled up to 11.
I did almost nothing to enable it.
Changed a flag in the command line to invoke Caddy, changed the URL in the Caddy configuration file from http to https.
In the background, Caddy requested and installed the certificates for me, and will continue to renew them before they expire.
SSL Everywhere is no longer a dream, it's real, it's here, and the tools couldn't be easier to use.
