= Getting Started With Go
:date: 2020/05/05 12:00:00
include::common/prelude.adoc[]

[background-color="#F25022"]
include::common/about.adoc[]

[transition=zoom, %notitle]
[background-color="#00A4EF"]
== Installing Go


Download and install Go - always use the packages from golang.org - never use homebrew or apt-get, yum, etc. They're broken, or worse -- modified by someone upstream.

== Installation Instructions

* https://bjk.fyi/go-mac[https://bjk.fyi/go-mac]
* https://bjk.fyi/go-linux[https://bjk.fyi/go-linux]
* https://bjk.fyi/go-windows[https://bjk.fyi/go-windows]


== Verify Your Installation

From your command prompt:

----
$ go version
----

You should see something like:

----
go version 1.14.2 linux/amd64
----


[transition=zoom, %notitle]
[background-color="#00A4EF"]
== Editing Go Code

* Visual Studio Code with `vscode-go`
* [neo]vim with `vim-go`
* emacs with `go-mode.el`
* Goland from IntelliJ

== The Playground
Even if you don't have an editor configured locally you can still play with Go from your browser.

https://play.golang.org

== Playground Limitations

The Go Playground is a web service that runs on golang.org's servers. The service receives a Go program, compiles, links, and runs the program inside a sandbox, then returns the output.

== Playground Limitations

The playground can use most of the standard library, with some exceptions. The only communication a playground program has to the outside world is by writing to standard output and standard error.

== Playground Limitations

In the playground the time begins at 2009-11-10 23:00:00 UTC (determining the significance of this date is an exercise for the reader). This makes it easier to cache programs by giving them deterministic output.

== Playground Limitations

There are also limits on execution time and on CPU and memory usage.

== Playground Limitations

Therefore: No file IO, nothing useful with time or dates, can't use any external packages.

== Go Playground


Even with all those limitations Go developers love the Go Playground - it's a great place to share code, even if it can't run or compile. You can enter code then click the "SHARE" button which will give you a permanent URL to that code.

Try it now with this link: 

https://bjk.fyi/hello-microsoft



include::common/thanks.adoc[]