= Syntax and Types
:date: 2020/05/06 12:00:00
include::common/prelude.adoc[]

[background-color="#F25022"]
include::common/about.adoc[]


[transition=zoom, %notitle]
[background-color="#00A4EF"]
== !

Go has built-in types that aren't surprising.

----
uint8       unsigned  8-bit integers (0 to 255)
uint16      unsigned 16-bit integers (0 to 65535)
uint32      unsigned 32-bit integers (0 to 4294967295)
uint64      unsigned 64-bit integers (0 to 18446744073709551615)
int8        signed  8-bit integers (-128 to 127)
int16       signed 16-bit integers (-32768 to 32767)
int32       signed 32-bit integers (-2147483648 to 2147483647)
int64       signed 64-bit integers (-9223372036854775808 to 9223372036854775807)
float32     IEEE-754 32-bit floating-point numbers
float64     IEEE-754 64-bit floating-point numbers
complex64   complex numbers with float32 real and imaginary parts
complex128  complex numbers with float64 real and imaginary parts
byte        alias for uint8
rune        alias for int32
----


== Implementation specific types

* 64 or 32 bit depending on platform
----
uint     either 32 or 64 bits
int      same size as uint
uintptr  unsigned integer (size of pointer)
----

[background-color="#F25022"]
== Warning

WARNING: On 64 bit system you might think that `int` and `int64` are the same type.

They hold the same data, but are distinct types.

== Beyond Numeric Types

string and bool

----
string  string values
bool    a boolean (true/false) value
----

[background-color="#00A4EF"]
== Declaring and Assigning Values to Variables

[background-color="#00A4EF"]
== Without Initialization 

++++
<pre><code data-sample='includes/syntaxtypes/includes/without/main.go#without'></code></pre>
++++

[background-color="#00A4EF"]
== With Initialization 

++++
<pre><code data-sample='includes/syntaxtypes/includes/with/main.go#with'></code></pre>
++++

[background-color="#00A4EF"]
== Implicit Type

++++
<pre><code data-sample='includes/syntaxtypes/includes/implicit/main.go#implicit'></code></pre>
++++

[background-color="#00A4EF"]
== !

All three produce an integer that is indistinguishable from the others. With the implicit declaration, the compiler determines the type of the variable at compile time (not run time).


== Zero Values in Go

All builtin types have a zero value. Any allocated variable is usable even if it never has a value assigned.

== Zero Values

++++
<pre><code data-sample='includes/syntaxtypes/includes/zero/main.go#zero'></code></pre>
++++

== !

++++
<pre><code data-sample='includes/syntaxtypes/includes/zero/main.go#zero'></code></pre>
++++
++++
<pre><code data-sample='includes/syntaxtypes/includes/zero/main.go#output'></code></pre>
++++

== ! 

|===
| Declaration | Zero Value
|var a int
|int [0]
|var b string
|string []
|var c float64
|float64 [0]
|var d bool
|bool [false]
|===

== Constants

Constants are variables that can't be modified at run time.

== Constant String
++++
<pre><code data-sample='includes/syntaxtypes/includes/constants/main.go#string'></code></pre>
++++

== Constant Int
++++
<pre><code data-sample='includes/syntaxtypes/includes/constants/main.go#number'></code></pre>
++++

Implict type

== Modification Error

https://play.golang.org/p/QbMYFA0a4i 

== Iota

Sometimes you want sequential constants:

++++
<pre><code data-sample='includes/syntaxtypes/includes/ugly/main.go#ugly'></code></pre>
++++

== Iota

Iota: compile time helper

++++
<pre><code data-sample='includes/syntaxtypes/includes/iota/main.go#iota'></code></pre>
++++

== !

++++
<pre><code data-sample='includes/syntaxtypes/includes/iota/main.go#iota'></code></pre>
++++

----
sunday = 0
monday = 1
----

== Skipping a value

Discard the first value with `_`
++++
<pre><code data-sample='includes/syntaxtypes/includes/iotaskip/main.go#skip'></code></pre>
++++

----
sunday = 1
monday = 2
----

== Structs

Structs are unique types with zero or more fields.

++++
<pre><code data-sample='includes/syntaxtypes/includes/structs/main.go#struct'></code></pre>
++++

== Struct Declaration

Declare with zero value:

++++
<pre><code data-sample='includes/syntaxtypes/includes/structs/main.go#zero'></code></pre>
++++

== Struct Declaration

Declare with literal value:

++++
<pre><code data-sample='includes/syntaxtypes/includes/structs/main.go#literal'></code></pre>
++++


include::common/thanks.adoc[]