:includedir: ../../common

= Code Like the Go Team

[background-color="#F25022"]
include::{includedir}/about.adoc[]

[transition=zoom, %notitle]
[background-color="#00A4EF"]
== Write Code Like the Go Team

* how to organize your code into packages, and what those packages should contain  
* code patterns and conventions that are prevalent in the standard library  
* how to write your code to be more clear and understandable  
* unwritten Go conventions that go beyond “go fmt” and make you look like a veteran Go contributor wrote it



[transition-speed=fast, %notitle]
[background-color="#737373"]
== Outline

* Packages
* Naming Conventions
* Source Code Conventions

[transition=zoom, %notitle]
[background-color="#00A4EF"]
== Packages


[background-color="#00A4EF", %notitle]
== Code Organization

There are two key areas of code organization in Go that will make a huge impact on the usability, testability, and functionality of your code:

[%step]
* Package Naming
* Package Organization


[background-color="#00A4EF", %notitle]
== Code Organization

We can't talk about them separately because one influences the other.


[background-color="#00A4EF", %notitle]
== Package Organization - Libraries

Packages contain code that has a single purpose

[source, bash]
----
archive	encoding reflect path syscall database  
----

[background-color="#00A4EF", %notitle]
== !

When a group of packages provides a common set of functionalities with different implementations, they're organized under a parent.  Look at the contents of package *encoding*:

[source, bash]
----
ascii85 base32 binary encoding go hex pem ...
----

[background-color="#00A4EF", %notitle]
== Commonalities

* Packages names describe their purpose
* It's very easy to see what a package does by looking at the name
* Names are generally short
* When necessary, use a descriptive parent package and several children implementing the functionality -- like the *encoding* package


[background-color="#7FBA00", %notitle]
== Package Organization - Applications

The packages we've seen are all libraries.  They're intended to be imported and used by some executable program like a service or command line tool.

What should the organization of your executable applications look like?


[background-color="#7FBA00", %notitle]
== !

When you have an application, the package organization is subtly different.  The difference is the command, the executable that ties all of those packages together.


[background-color="#7FBA00", %notitle]
== !

Application package organization has a huge impact on the testability and functionality of your system.


[background-color="#7FBA00", %notitle]
== !


When writing an application your goal should be to write code that is easy to understand, easy to refactor, and easy for someone else to maintain.


[background-color="#7FBA00", %notitle]
== !

Most libraries focus on providing a singularly scoped function; logging, encoding, network access.

Your application will tie all of those libraries together to create a tool or service.  That tool or service will be much larger in scope.  

[background-color="#7FBA00", %notitle]
== !

When you're building an application, you should organize your code into packages, but those packages should be centered on two categories:

- Domain Types
- Services


[background-color="#7FBA00", %notitle]
== !

*Domain Types* are types that model your business functionality and objects. 

*Services* are packages that operate on or with the domain types.

https://medium.com/@benbjohnson/standard-package-layout-7cdbc8391fc1


[background-color="#7FBA00", %notitle]
== !

A domain type is the substance of your application.  If you have an inventory application, your domain types might include *Product* and *Supplier*.  If you have an HR administration system, your domain types might include *Employee*, *Department*, and *Business Unit*.


[background-color="#7FBA00", %notitle]
== !

The package containing your domain types should also define the interfaces between your domain types and the rest of the world.  These interfaces define the things you want to do with your domain types.

- *ProductService*  
- *SupplierService*
- *AuthenticationService*
- *EmployeeStorage*
- *RoleStorage*

[background-color="#7FBA00", %notitle]
== !

Your domain type package should be the root of your application repository.  This makes it clear to anyone opening the codebase what types are being used, and what operations will be performed on those types.


[background-color="#7FBA00", %notitle]
== !

The domain type package, or *root* package of your application should not have any external dependencies.  

TIP:  It exists for the sole purpose of describing your types and their behaviors.

[background-color="#7FBA00", %notitle]
== !

The implementations of your domain interfaces should be in separate packages, organized by dependency.

[background-color="#7FBA00", %notitle]
== !

Dependencies include:

* External data sources
* Transport logic (http, RPC)

TIP: You should have one package per dependency.


[background-color="#7FBA00", %notitle]
== !

Why one package per dependency?

[%step]
* Simple testing
* Easy substitution/replacement
* No circular dependencies


== Conventions

== !

.Naming Conventions
[quote, Every Developer Ever, Twitter]
____
there are two hard things in computer science:
cache invalidation, naming things, and off-by-one errors
____

== !

Naming things *is* hard, but putting some thought into your type, function, and package names will make your code more readable


== Packages

A package name should have the following characteristics:

* short 
** Prefer "transport" over "transportmechanisms"
* clear 
** Name for clarity based on function: "bytes" 
** Name to describe implementation of external dependency: "postgres" 

== !

Packages should provide functionality for one and only one purpose.  Avoid *catch-all* packages:

* util
* helpers

TIP: Frequently they're a sign that you're missing an interface somewhere.

== !

`util.ConvertOtherToThing()` should probably be refactored into a *Thinger* interface.

*catchall* packages are always the first place you'll run into problems with testing and circular dependencies, too.

== Naming Conventions - Variables

* use `camelCase` not `snake_case`
* use single letter variables to represent indexes
** `for i:=0; i < 10; i++ {}`
* use short but descriptive variable names for other things
** `var count int`
** `var cust Customer`

== !

There are no bonus points in Go for obfuscating your code by using unnecessarily short variables.  Use the scope of the variable as your guide.  The farther away from declaration you use it, the longer the name should be.


== !


* use repeated letters to represent a collection/slice/array
** `var tt []*Thing`
* inside a loop/range, use the single letter
** `for i, t := range tt {}`

These conventions are common inside Go's own source code.

== Functions

Avoid a package-level function name that repeats the package name.  

WARNING:   log.LogInfo()

The package name already declares the purpose of the package, so there's no need to repeat it.

== Functions

Better:

TIP:  log.Info()

== Methods

Go code doesn't have setters and getters.

WARNING:   invoice.GetCustomer()

== Methods

Better:

TIP:   invoice.Customer()

== Interfaces

If your interface has only one function, append "-er" to the function name:

[source, go]
----
type Stringer interface{
    String() string
}
----

== !

If your interface has more than one function, use a name to represent its functionality:

[source, go]
----
type CustomerStorage interface {
    Customer(id int) (*Customer, error)
    Save(c *Customer)  error
    Delete(id int) error
}
----

== !

Some purists think that all interfaces should end in `-er`.  I think interfaces should be descriptive and readable.  

[source, go]
----
type CustomerStorer interface {} // MEH
type CustomerStorage interface {} // Better
----

== Naming - Source Code

Inside a package separate code into logical concerns.

If the package deals with multiple types, keep the logic for each type in its own source file:

[source]
----
package: postgres

orders.go
suppliers.go
products.go
----

== !

In the package that defines your domain objects, define the types and interfaces for each object in the same source file:

[source]
----
	package: inventory

	orders.go 
----

contains *Orders* type and *OrderStorage* interface

== Smaller Tips

Make comments in full sentences, always.

[source,go]
----
// An Order represents an order from a customer.
type Order struct {}
----

== !

Use `goimports` to manage your imports, and they'll always be in canonical order. Standard lib first, external next. 


== !

Avoid the `else` clause.  Especially in error handling.  

[source,go]
----
if err != nil {
    // error handling
    return // or continue, etc.
} 
// normal code
----


[background-color="#00A4EF"]
== Code Like the Go Team

Following these conventions will make your source code easier to read, easier to maintain, and easier for someone else to understand.

include::{includedir}/thanks.adoc[]
