name = "brianketelsen"
type = "webpack"
account_id = "ada37dcd6014ac51906845ec06d78079"
workers_dev = true
route = ""
zone_id = ""

[site]
bucket = "./public"
entry-point = "workers-site"

[env.production]
# The ID of your domain you're deploying to
zone_id = "f1b855f071b25dfdf1d009526f323019"
# The route pattern your Workers application will be served at
route = "brianketelsen.com/*"